### ISSUE TITLE
 resulted in a `403 Forbidden

### ISSUE THREAD

**Issue by david34corbalan** [sunaoka/laravel-ses-template-driver#4]
hello, I have an error when I use the package, which gives error 403, making all the configurations that are here.
![Captura de Pantalla 2021-07-30 a la(s) 17 29 51](https://user-images.githubusercontent.com/43279485/127708475-37ceb442-39d9-432a-8efc-a54fbf9e86ac.png)
![Captura de Pantalla 2021-07-30 a la(s) 17 30 00](https://user-images.githubusercontent.com/43279485/127708493-a83f2b2b-3e4e-4aec-8637-2f9a2a771e8a.png)
![Captura de Pantalla 2021-07-30 a la(s) 17 30 16](https://user-images.githubusercontent.com/43279485/127708525-1727aeb5-c4d6-4b8e-8e7b-c2d035979202.png)

in the version of laravel 5.8 it works. help me, please.

**Comment by sunaoka** [comment]
Please grant `ses:SendTemplatedEmail` permission to the AWS role.
Also, please use an email address that is authorized by SES.
